---
- name: Configuration for new linux install
  hosts: localhost
  vars:
    debug_flag: false
  vars_files:
    - vars.yaml
  tasks:
    - name: print facts
      ansible.builtin.debug:
        var: ansible_os_family
      when: debug_flag

    - name: Arch specific config
      import_tasks:
        file: tasks/arch.yaml
      when: ansible_os_family == "Archlinux"
      become: true

    - name: Debian specific config
      import_tasks:
        file: tasks/debian.yaml
      when: ansible_os_family == "Debian"
      become: true

    - name: RedHat specific config
      import_tasks:
        file: tasks/redhat.yaml
      when: ansible_os_family == "RedHat"
      become: true

    - name: Set zshell
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        shell: /bin/zsh
      become: true

    - name: Install Tmux package manager
      ansible.builtin.git:
        dest: "{{ansible_env.HOME}}/.tmux/plugins/tpm"
        repo: https://github.com/tmux-plugins/tpm
