---
- name: Configuration for new linux install
  hosts: localhost
  vars:
    debug_flag: True
  vars_files:
    - vars.yaml
  tasks:
    - name: print facts
      ansible.builtin.debug:
        var: ansible_os_family
      when: debug_flag

    - name: Arch specific config
      import_tasks:
        file: tasks/arch.yaml
      when: ansible_os_family == "Archlinux"

    - name: Debian specific config
      import_tasks:
        file: tasks/debian.yaml
      when: ansible_os_family == "Debian"

    - name: RedHat specific config
      import_tasks:
        file: tasks/redhat.yaml
      when: ansible_os_family == "RedHat"

    - name: Set zshell
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        shell: /bin/zsh
      become: true

    - name: Install Tmux package manager
      ansible.builtin.git:
        dest: "{{ansible_env.HOME}}/.tmux/plugins/tpm"
        repo: https://github.com/tmux-plugins/tpm

    - name: Configure git editor
      community.general.git_config:
        name: core.editor
        scope: system
        value: nvim
      become: true

    - name: Config git email 
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ email }}"

    - name: Config git name
      community.general.git_config:
        name: user.name
        scope: global
        value: "Kyle Wendholt"
