---
- name: Update packages/cache
  community.general.pacman:
    update_cache: true
    update: true
  become: true

- name: Install packages
  community.general.pacman:
    name:
      - git
      - fzf
      - neovim
      - tmux
      - lazygit
      - ripgrep
      - zsh
  become: true
