---
- name: Copy dot files over
  ansible.builtin.copy:
    src: ../config_files
    dest: "{{ ansible_env.HOME }}/.config"

- name: Copy zshrc over
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"

- name: Configure git editor
  community.general.git_config:
    name: core.editor
    scope: system
    value: nvim

- name: Config git email 
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ email }}"

- name: Config git name
  community.general.git_config:
    name: user.name
    scope: global
    value: "Kyle Wendholt"
