- name: Update all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
  become: true

- name: Enable lazygit copr repo
  community.general.copr:
    host: atim/lazygit

- name: Install packages
  ansible.builtin.dnf:
    name:
      - git
      - fzf
      - neovim
      - tmux
      - lazygit
      - ripgrep
      - zsh
  become: true
