- name: Upgrade distro
  ansible.builtin.apt:
    upgrade: dist
  become: true

- name: Update all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
  become: true

- name: Install packages
  ansible.builtin.apt:
    pkg:
      - git
      - fzf
      - neovim
      - tmux
      - lazygit
      - ripgrep
      - zsh
  become: true
