---
- name: Configuration for new linux install
  hosts: localhost
  vars_prompt:
    - name: email
      prompt: "Input Email:"
  tasks:
    - name: print facts
      ansible.builtin.debug:
        var: ansible_os_family

    - name: Arch specific config
      import_tasks:
        file: arch.yaml
      when: ansible_os_family == "Archlinux"

    - name: Debian specific config
      import_tasks:
        file: debian.yaml
      when: ansible_os_family == "Debian"

    - name: RedHat specific config
      import_tasks:
        file: redhat.yaml
      when: ansible_os_family == "RedHat"

    - name: Configure dotfiles
      import_tasks:
        file: dotfiles.yaml
